### ISSUE TITLE
Google login

### ISSUE THREAD

**Issue by tutugodfrey** [andela/rivendell-ah-client#16]
This is what I get when I try to login with google.
![image](https://user-images.githubusercontent.com/30448913/45482591-6c74fc80-b746-11e8-9fde-6425ae56ef62.png)

and this for facebook
![image](https://user-images.githubusercontent.com/30448913/45483031-a1358380-b747-11e8-8dda-f674b8e97ffa.png)

and for LinkedIn
![image](https://user-images.githubusercontent.com/30448913/45483066-bd392500-b747-11e8-823c-368453718ca8.png)

Is this how you expected the functionality to behave? If not what is wrong here or What should I do differently.

**Comment by JCanaks** [comment]
Have you pulled the new updates on the backend staging to your local staging?? There are some recent updates on the backend staging that you should pull to your local staging. In order to get the proper response on successful login.

**Comment by tutugodfrey** [comment]
Ok! I will check it out then.
